# Use a lightweight JDK 17 image
FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the Gradle build directory into the container
COPY ./build/libs/*.jar app.jar

EXPOSE 1211

# Run the Kotlin Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
